# This is a basic workflow that is manually triggered



name: Manual workflow


# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
      - feat**
      - bug**
      - task**
    paths-ignore:
      - 'docs/**'
    tags:
      - v*
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      deploy_environment:
        description: 'what is target environment to deploy latest? i.e., kalm-main-16-4'
        type: string
        required: true
      github_environment:
        description: 'Github environment secrets location.'
        default: 'kalm-main-cicd'
        type: environment
        required: true
      github_runner:
        description: 'Runner runner label'
        default: 'ubuntu-latest'
        type: environment
        required: true

env:
  ### Target karbon production environment / hpoc id
  ENVIRONMENT_NAME: ${{ github.event.inputs.deploy_environment || 'kalm-main-16-4' }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet:
    # The type of runner that the job will run on
    runs-on: ${{ github.event.inputs.github_runner || 'ubuntu-latest' }}
    # This workflow contains a single job called "greet"
    environment:
      name: ${{ github.event.inputs.github_environment || 'kalm-main-cicd' }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell 
    - name: Dump GitHub context
      id: github_context_step
      run: echo '${{ toJSON(github) }}'
    - name: Dump job context
      run: echo '${{ toJSON(job) }}'
    - name: Dump step context
      run: echo '${{ toJSON(steps) }}'
    - name: Dump secrets context
      run: echo '${{ toJSON(secrets) }}'
    - name: Echo Environment
      run: echo $ENVIRONMENT_NAME
    
    
