# This is a basic workflow that is manually triggered



name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment_name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'what is environment name'
        # Default value if no value is explicitly provided
        default: 'kalm-main-8-2'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: '${{ github.event.inputs.environment_name }}'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"     
    - name: Dump GitHub context
      id: github_context_step
      run: echo '${{ toJSON(github) }}'
    - name: Dump job context
      run: echo '${{ toJSON(job) }}'
    - name: Echo Environment Name
      run: echo '${{ github.event.inputs.environment_name }}'
    - name: Echo Environment
      run: echo '${{ github.event.inputs.environment }}'
    - name: Echo Environment Specific Secret
      run: echo '${{ secrets.COMMON_SECRET }}'
    
