# This is a basic workflow that is manually triggered



name: Manual workflow


# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
      - feat**
      - bug**
      - task**
    paths-ignore:
      - 'docs/**'
    tags:
      - v*
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      target_environment:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'what is target environment name'
        # Default value if no value is explicitly provided
        default: 'kalm-main-x-y'
        # Input has to be provided for the workflow to run
        required: true


env:
  ### Target karbon production environment / hpoc id
  ENVIRONMENT_NAME: ${{ github.event.inputs.target_environment || 'kalm-main-16-4' }}
  GH_RUNNER_ENVIRONMENT: ${{ github.event.inputs.target_environment || 'kalm-main-cicd' }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # This workflow contains a single job called "greet"
    environment: $GH_RUNNER_ENVIRONMENT
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell 
    - name: Dump GitHub context
      id: github_context_step
      run: echo '${{ toJSON(github) }}'
    - name: Dump job context
      run: echo '${{ toJSON(job) }}'
    - name: Echo Environment
      run: echo $ENVIRONMENT_NAME
    - name: Echo Github Runner Self-Hosted Environment
      run: echo $GH_RUNNER_ENVIRONMENT
    
