# This is a basic workflow that is manually triggered



name: Manual workflow


# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
      - feat**
      - bug**
      - task**
    paths-ignore:
      - 'docs/**'
    tags:
      - v*
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      deploy_environment:
        description: 'what is target environment to deploy latest?'
        default: 'kalm-main-16-4'
        type: string
        required: true
      github_environment:
        description: 'Github environment to pull secrets from...'
        default: 'kalm-main-cicd'
        type: environment
        required: true


env:
  ### Target karbon production environment / hpoc id
  ENVIRONMENT_NAME: ${{ github.event.inputs.deploy_environment || 'kalm-main-16-4' }}
  GH_ENVIRONMENT: ${{ github.event.inputs.github_environment || 'kalm-main-cicd' }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # This workflow contains a single job called "greet"
    environment:
      name: ${{ github.env.ENVIRONMENT_NAME }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell 
    - name: Dump GitHub context
      id: github_context_step
      run: echo '${{ toJSON(github) }}'
    - name: Dump job context
      run: echo '${{ toJSON(job) }}'
    - name: Dump steps context
      run: echo '${{ toJSON(steps.environment.name) }}'
    - name: Echo Environment
      run: echo $ENVIRONMENT_NAME
    - name: Echo Github Runner Self-Hosted Environment
      run: echo $GH_ENVIRONMENT
    - name: Echo Github Environment
      run: echo '${{ steps.environment.outputs }}'
    
    
